vich_uploader:
    db_driver: orm

    mappings:
      profile_users:
         uri_prefix: '%profile_users%'
         upload_destination: '%kernel.project_dir%/public%profile_users%'
         namer:
            service: Vich\UploaderBundle\Naming\UniqidNamer
         delete_on_update: false
         delete_on_remove: false

      library:
         uri_prefix: '%library%'
         upload_destination: '%kernel.project_dir%/public%library%'
         namer:
            service: Vich\UploaderBundle\Naming\UniqidNamer
         delete_on_update: false
         delete_on_remove: false
      
      lesson_pdf:
         uri_prefix: '%lesson_pdf%'
         upload_destination: '%kernel.project_dir%/public%lesson_pdf%'
         namer:
            service: Vich\UploaderBundle\Naming\PropertyNamer
            options: { property: 'slug'}
         delete_on_update: false
         delete_on_remove: false

      formation_images:
            uri_prefix: '%formation_images%'
            upload_destination: '%kernel.project_dir%/public%formation_images%'
            namer:
               service: Vich\UploaderBundle\Naming\PropertyNamer
               options: { property: 'slug'}
            delete_on_update: false
            delete_on_remove: false

      lesson_images:
            uri_prefix: '%lesson_images%'
            upload_destination: '%kernel.project_dir%/public%lesson_images%'
            namer:
               service: Vich\UploaderBundle\Naming\PropertyNamer
               options: { property: 'slug'}
            delete_on_update: false
            delete_on_remove: false      

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
