vich_uploader:
    db_driver: orm

    mappings:
       formation_images:
            uri_prefix: '%formation_images%'
            upload_destination: '%kernel.project_dir%/public%formation_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        
       lesson_images:
            uri_prefix: '%lesson_images%'
            upload_destination: '%kernel.project_dir%/public%lesson_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
